version: "3.9"
services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo/dantri
    restart: always
  mongo:
    image: mongo:4.2.18-rc0-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
